test 2
PS C:\Users\daniy\OneDrive\Documents\GitHub\markdown-parser> java .\MarkdownParse.class .\ptest3.md
Error: Could not find or load main class .\MarkdownParse.class
Caused by: java.lang.ClassNotFoundException: /\MarkdownParse/class